BEGIN;

CREATE TABLE IF NOT EXISTS carreras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(16) NOT NULL UNIQUE,
  nombre VARCHAR(180) NOT NULL,
  semestres INTEGER NOT NULL CHECK (semestres > 0),
  descripcion TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  es_boceto BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS areas_academicas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrera_id BIGINT NOT NULL REFERENCES carreras(id) ON DELETE CASCADE,
  nombre VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_area_por_carrera UNIQUE (carrera_id, nombre)
);

CREATE TABLE IF NOT EXISTS materias (
  codigo VARCHAR(32) PRIMARY KEY,
  carrera_id BIGINT NOT NULL REFERENCES carreras(id) ON DELETE CASCADE,
  area_id BIGINT REFERENCES areas_academicas(id) ON DELETE SET NULL,
  nombre VARCHAR(180) NOT NULL,
  semestre INTEGER NOT NULL CHECK (semestre > 0),
  tipo_valor VARCHAR(4) NOT NULL CHECK (tipo_valor IN ('CR', 'TH')),
  creditos NUMERIC(6,2),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  carga_horaria_total INTEGER,
  horas_teoricas INTEGER,
  horas_practicas INTEGER,
  fuente VARCHAR(80) NOT NULL DEFAULT 'carreras.pdf',
  es_boceto BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS materias_prerrequisito (
  materia_codigo VARCHAR(32) NOT NULL REFERENCES materias(codigo) ON DELETE CASCADE,
  prerrequisito_codigo VARCHAR(32) NOT NULL REFERENCES materias(codigo) ON DELETE CASCADE,
  nota TEXT,
  PRIMARY KEY (materia_codigo, prerrequisito_codigo)
);

CREATE TABLE IF NOT EXISTS usuarios (
  ci VARCHAR(20) PRIMARY KEY,
  rol VARCHAR(20) NOT NULL CHECK (rol IN ('estudiante', 'docente', 'admin')),
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS estudiantes (
  usuario_ci VARCHAR(20) PRIMARY KEY REFERENCES usuarios(ci) ON DELETE CASCADE,
  carrera_id BIGINT REFERENCES carreras(id) ON DELETE SET NULL,
  registro VARCHAR(40) UNIQUE,
  fecha_ingreso DATE
);

CREATE TABLE IF NOT EXISTS docentes (
  usuario_ci VARCHAR(20) PRIMARY KEY REFERENCES usuarios(ci) ON DELETE CASCADE,
  carrera_id BIGINT REFERENCES carreras(id) ON DELETE SET NULL,
  codigo_docente VARCHAR(40) UNIQUE
);

CREATE TABLE IF NOT EXISTS cursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  materia_codigo VARCHAR(32) REFERENCES materias(codigo) ON DELETE SET NULL,
  carrera_id BIGINT REFERENCES carreras(id) ON DELETE SET NULL,
  docente_ci VARCHAR(20) NOT NULL REFERENCES usuarios(ci) ON DELETE RESTRICT,
  codigo VARCHAR(40) NOT NULL UNIQUE,
  nombre VARCHAR(180) NOT NULL,
  periodo VARCHAR(30) NOT NULL,
  gestion INTEGER NOT NULL,
  cupo INTEGER NOT NULL DEFAULT 40,
  fecha_inicio DATE,
  fecha_fin DATE,
  estado VARCHAR(20) NOT NULL DEFAULT 'activo',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS curso_estudiantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
  estudiante_ci VARCHAR(20) NOT NULL REFERENCES usuarios(ci) ON DELETE CASCADE,
  estado VARCHAR(20) NOT NULL DEFAULT 'inscrito',
  fecha_inscripcion TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_curso_estudiante UNIQUE (curso_id, estudiante_ci)
);

CREATE TABLE IF NOT EXISTS calificaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id BIGINT NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
  estudiante_ci VARCHAR(20) NOT NULL REFERENCES usuarios(ci) ON DELETE CASCADE,
  nota_final NUMERIC(5,2),
  observaciones TEXT,
  estado_nota VARCHAR(20) NOT NULL DEFAULT 'registrada',
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_calificacion_por_curso UNIQUE (curso_id, estudiante_ci)
);

CREATE INDEX IF NOT EXISTS idx_materias_carrera_semestre ON materias (carrera_id, semestre);
CREATE INDEX IF NOT EXISTS idx_cursos_docente ON cursos (docente_ci, gestion, periodo);
CREATE INDEX IF NOT EXISTS idx_curso_estudiantes_estudiante ON curso_estudiantes (estudiante_ci, estado);
CREATE INDEX IF NOT EXISTS idx_calificaciones_curso_estudiante ON calificaciones (curso_id, estudiante_ci);

COMMIT;
